language: go
sudo: false
go:
  - 1.x
before_install:
  - go get github.com/mattn/goveralls
  - openssl aes-256-cbc -K $encrypted_651794928adc_key -iv $encrypted_651794928adc_iv -in test-backup-validator-auth.json.travenc -out test-backup-validator-auth.json -d
script:
  - $GOPATH/bin/goveralls -service=travis-ci -ignore=main.go
