version: 0.0.{build}
image: Visual Studio 2017
clone_folder: c:\gopath\src\github.com\mattgiltaji\validatebackups
environment:
  GOPATH: c:\gopath
install:
- cmd: >-
    echo %PATH%

    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

    go version

    go env
build_script:
- cmd: >-
    go get -v -d ./...

    go build -o buildOutput\validatebackups.exe -i .
test_script:
- cmd: >-
    go get -v -t -d ./...

    go test -v -race ./...
artifacts:
- path: buildOutput\validatebackups.exe
  name: validatebackups.exe