version: 0.0.{build}
image: Visual Studio 2019
clone_folder: c:\gopath\src\github.com\mattgiltaji\validatebackups
environment:
  GOPATH: c:\gopath
  secret:
    secure: ZR7JKuioQ54LgmkkSi2fIPLZmwgchE6mynve2CSI2Xw=
  salt:
    secure: xnwOXdx6jc3yaHZU+29Ti56jvXZ+VTCVDJ2figaUSSX9ru9yZPdXeP1l0gSekcrxat9oSEFyPZscLbUxC41ncQ==
install:
- ps: >-
    iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))

    appveyor-tools\secure-file -decrypt  "$Env:APPVEYOR_BUILD_FOLDER\test-backup-validator-auth.json.enc" -secret $Env:secret -salt $Env:salt -out "$Env:APPVEYOR_BUILD_FOLDER\test-backup-validator-auth.json"

    echo "$Env:PATH"

    echo "$Env:GOPATH"

    $Env:PATH = "$Env:GOPATH\bin;$Env:PATH"

    go version

    go env
build_script:
- cmd: >-
    go get -v -d ./...

    go build -o buildOutput\validatebackups.exe .
test_script:
- cmd: >-
    go get -v -t -d ./...

    go test -v ./...
artifacts:
- path: buildOutput\validatebackups.exe
  name: validatebackups.exe