version: 0.0.{build}
image: Visual Studio 2019
clone_folder: c:\gopath\src\github.com\mattgiltaji\validatebackups
environment:
  GOPATH: c:\gopath
  secret_key:
    secure: YdUmnIWk1uCQalq497dt8DbeU7RZnlJ1sn3Zl0+wCUI=
install:
- ps: >-
    iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
    
    appveyor-tools\secure-file -decrypt  "$Env:GOPATH\test-backup-validator-auth.json.appenc" -secret $Env:secret_key -out "$Env:GOPATH\test-backup-validator-auth.json"

    echo $Env:PATH
    echo $Env:GOPATH
  
    $Env:PATH = "$Env:GOPATH\bin;$Env:PATH;C:\msys64\mingw64\bin"

    go version
    go env
build_script:
- cmd: >-
    go get -v -d ./...

    go build -o buildOutput\validatebackups.exe .
test_script:
- cmd: >-
    go get -v -t -d ./...

    go test -v ./...
artifacts:
- path: buildOutput\validatebackups.exe
  name: validatebackups.exe